### ISSUE TITLE
Google docs spreadsheet

### ISSUE THREAD

**Issue by raemacias** [raemacias/housing#18]

**Comment by kmccardwell** [comment]
https://docs.google.com/spreadsheets/d/1e363-M4cilPr5PKLEJl4WjUsI69h51px7Gnwox8W1IY/edit#gid=0
Spreadsheet for dumping results of calls/forms

**Comment by kmccardwell** [comment]
Just kidding: made private (share link), new link: https://docs.google.com/spreadsheets/d/1e363-M4cilPr5PKLEJl4WjUsI69h51px7Gnwox8W1IY/edit?usp=sharing
